service: meufan-poc

provider:
  name: aws
  runtime: python3.9
  apiGateway:
    apiKeys:
      - meufanApiKey
    usagePlan:
      quota:
        limit: 5000
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  environment:
    ONBOARDING_TABLE: lista_onboarding-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - OnboardingTable
          - Arn

functions:
  get_survey:
    handler: handler.get_survey
    events:
      - http:
          path: survey/{id}
          method: get
          private: true # Requer API Key
          request:
            parameters:
              paths:
                id: true
                
  list_surveys:
    handler: handler.list_surveys
    events:
      - http:
          path: surveys
          method: get
          private: true # Requer API Key

package:
  patterns:
    - "!venv/**"
    - "!_ignore/**"
    - "!__pycache__/**"
    - "!test*/**"
    - "!.git/**"

resources:
  Resources:
    OnboardingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ONBOARDING_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH